# Generated by Django 4.2.7 on 2025-08-01 05:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cancha",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre o número de la cancha",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Número de identificación", unique=True
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Interior", "Interior"),
                            ("Exterior", "Exterior"),
                            ("Cubierta", "Cubierta"),
                        ],
                        default="Exterior",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Ocupada", "Ocupada"),
                            ("Mantenimiento", "Mantenimiento"),
                            ("Fuera_Servicio", "Fuera de Servicio"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción o características especiales"
                    ),
                ),
                (
                    "capacidad_espectadores",
                    models.PositiveIntegerField(
                        default=0, help_text="Capacidad de espectadores"
                    ),
                ),
                ("tiene_iluminacion", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cancha",
                "verbose_name_plural": "Canchas",
                "db_table": "canchas",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Juego",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_juego", models.PositiveIntegerField()),
                ("puntos_equipo1", models.PositiveIntegerField(default=0)),
                ("puntos_equipo2", models.PositiveIntegerField(default=0)),
                ("finalizado", models.BooleanField(default=False)),
                (
                    "equipo_ganador",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "equipo_que_saca",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "juegos",
                "ordering": ["numero_juego"],
            },
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual (1 vs 1)"),
                            ("Dobles", "Dobles (2 vs 2)"),
                        ],
                        default="Dobles",
                        help_text="Individual (1vs1) o Dobles (2vs2)",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En Juego", "En Juego"),
                            ("Finalizado", "Finalizado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Amistoso", "Amistoso"),
                            ("Torneo", "Torneo"),
                            ("RANK", "RAKING"),
                        ],
                        default="Amistoso",
                        max_length=10,
                    ),
                ),
                (
                    "sets_para_ganar",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("juegos_para_ganar_set", models.PositiveIntegerField(default=6)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "equipo_ganador",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "cancha",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cancha donde se juega el partido",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partidos",
                        to="scoring.cancha",
                    ),
                ),
                (
                    "jugador1_equipo1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_j1_e1",
                        to="players.jugador",
                    ),
                ),
                (
                    "jugador1_equipo2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_j1_e2",
                        to="players.jugador",
                    ),
                ),
                (
                    "jugador2_equipo1",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo requerido para partidos de dobles",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_j2_e1",
                        to="players.jugador",
                    ),
                ),
                (
                    "jugador2_equipo2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo requerido para partidos de dobles",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_j2_e2",
                        to="players.jugador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "db_table": "partidos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_set",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("juegos_equipo1", models.PositiveIntegerField(default=0)),
                ("juegos_equipo2", models.PositiveIntegerField(default=0)),
                ("finalizado", models.BooleanField(default=False)),
                (
                    "equipo_ganador",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                ("tiene_tiebreak", models.BooleanField(default=False)),
                ("puntos_tiebreak_equipo1", models.PositiveIntegerField(default=0)),
                ("puntos_tiebreak_equipo2", models.PositiveIntegerField(default=0)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="scoring.partido",
                    ),
                ),
            ],
            options={
                "db_table": "sets",
                "ordering": ["numero_set"],
                "unique_together": {("partido", "numero_set")},
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo_reserva",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(help_text="Fecha y hora de inicio"),
                ),
                ("fecha_fin", models.DateTimeField(help_text="Fecha y hora de fin")),
                (
                    "duracion_minutos",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Duración en minutos",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Confirmada", "Confirmada"),
                            ("En_Uso", "En Uso"),
                            ("Completada", "Completada"),
                            ("Cancelada", "Cancelada"),
                            ("No_Show", "No Show"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_reserva",
                    models.CharField(
                        choices=[
                            ("Individual", "Práctica Individual"),
                            ("Dobles", "Práctica Dobles"),
                            ("Clase", "Clase/Entrenamiento"),
                            ("Torneo", "Torneo"),
                            ("Evento", "Evento Especial"),
                        ],
                        default="Dobles",
                        max_length=20,
                    ),
                ),
                (
                    "precio_hora",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Precio por hora en COP",
                        max_digits=8,
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Precio total de la reserva",
                        max_digits=8,
                    ),
                ),
                ("pagado", models.BooleanField(default=False)),
                (
                    "numero_jugadores",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Número de jugadores esperados",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones de la reserva"
                    ),
                ),
                (
                    "equipamiento_incluido",
                    models.BooleanField(
                        default=False, help_text="¿Incluye raquetas/pelotas?"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.CharField(
                        blank=True,
                        help_text="Usuario que creó la reserva",
                        max_length=100,
                    ),
                ),
                (
                    "cancha",
                    models.ForeignKey(
                        help_text="Cancha reservada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="scoring.cancha",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        help_text="Jugador que hace la reserva",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="players.jugador",
                    ),
                ),
                (
                    "partido",
                    models.OneToOneField(
                        blank=True,
                        help_text="Partido asociado (si aplica)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserva",
                        to="scoring.partido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "db_table": "reservas",
                "ordering": ["fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Punto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "equipo_ganador",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                (
                    "tipo_punto",
                    models.CharField(
                        choices=[("Punto", "Punto"), ("Deshacer", "Deshacer Punto")],
                        default="Punto",
                        max_length=10,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("numero_punto", models.PositiveIntegerField()),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos",
                        to="scoring.juego",
                    ),
                ),
            ],
            options={
                "db_table": "puntos",
                "ordering": ["numero_punto"],
            },
        ),
        migrations.AddField(
            model_name="juego",
            name="set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="juegos",
                to="scoring.set",
            ),
        ),
        migrations.CreateModel(
            name="EstadisticasJugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("partidos_ganados", models.PositiveIntegerField(default=0)),
                ("partidos_perdidos", models.PositiveIntegerField(default=0)),
                ("sets_jugados", models.PositiveIntegerField(default=0)),
                ("sets_ganados", models.PositiveIntegerField(default=0)),
                ("sets_perdidos", models.PositiveIntegerField(default=0)),
                ("juegos_jugados", models.PositiveIntegerField(default=0)),
                ("juegos_ganados", models.PositiveIntegerField(default=0)),
                ("juegos_perdidos", models.PositiveIntegerField(default=0)),
                ("puntos_jugados", models.PositiveIntegerField(default=0)),
                ("puntos_ganados", models.PositiveIntegerField(default=0)),
                ("puntos_perdidos", models.PositiveIntegerField(default=0)),
                ("racha_actual_victorias", models.PositiveIntegerField(default=0)),
                ("mejor_racha_victorias", models.PositiveIntegerField(default=0)),
                ("racha_actual_derrotas", models.PositiveIntegerField(default=0)),
                ("primer_partido", models.DateTimeField(blank=True, null=True)),
                ("ultimo_partido", models.DateTimeField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "jugador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estadisticas",
                        to="players.jugador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadísticas de Jugador",
                "verbose_name_plural": "Estadísticas de Jugadores",
                "db_table": "estadisticas_jugadores",
            },
        ),
        migrations.AlterUniqueTogether(
            name="juego",
            unique_together={("set", "numero_juego")},
        ),
        migrations.CreateModel(
            name="HistorialJugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_ganador", models.BooleanField()),
                (
                    "equipo_jugador",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                ("sets_ganados", models.PositiveIntegerField(default=0)),
                ("sets_perdidos", models.PositiveIntegerField(default=0)),
                ("juegos_ganados", models.PositiveIntegerField(default=0)),
                ("juegos_perdidos", models.PositiveIntegerField(default=0)),
                ("puntos_ganados", models.PositiveIntegerField(default=0)),
                ("puntos_perdidos", models.PositiveIntegerField(default=0)),
                ("fecha_partido", models.DateTimeField()),
                ("duracion_partido", models.DurationField(blank=True, null=True)),
                (
                    "Pareja",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compañero de equipo (solo en partidos de dobles)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compañeros_historial",
                        to="players.jugador",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="players.jugador",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiales",
                        to="scoring.partido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Jugador",
                "verbose_name_plural": "Historiales de Jugadores",
                "db_table": "historial_jugadores",
                "ordering": ["-fecha_partido"],
                "unique_together": {("jugador", "partido")},
            },
        ),
    ]
