# Generated by Django 4.2.7 on 2025-08-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="diferencia_minima_juegos",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="partido",
            name="diferencia_minima_puntos",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="partido",
            name="puntos_para_ganar_juego",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="partido",
            name="juegos_para_ganar_set",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="partido",
            name="sets_para_ganar",
            field=models.IntegerField(default=2),
        ),
    ]
