# Generated by Django 4.2.7 on 2025-08-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
        ("scoring", "0002_partido_diferencia_minima_juegos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historialjugador",
            name="jugador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="players.jugador",
            ),
        ),
        migrations.AlterField(
            model_name="historialjugador",
            name="partido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historiales",
                to="scoring.partido",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="jugador",
            field=models.ForeignKey(
                blank=True,
                help_text="Jugador que hace la reserva",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="players.jugador",
            ),
        ),
    ]
