# Generated by Django 4.2.7 on 2025-08-02 04:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseTorneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Grupos', 'Fase de Grupos'), ('Eliminacion', 'Eliminación Directa'), ('Final', 'Final'), ('Clasificacion', 'Partido por Clasificación')], max_length=20)),
                ('nombre', models.CharField(help_text='Ej: Cuartos de Final, Grupo A', max_length=50)),
                ('orden', models.PositiveIntegerField(help_text='Orden de la fase en el torneo')),
                ('activa', models.BooleanField(default=False)),
                ('completada', models.BooleanField(default=False)),
                ('numero_ronda', models.PositiveIntegerField(blank=True, help_text='Para eliminación: 1=Final, 2=Semis, 3=Cuartos...', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fase de Torneo',
                'verbose_name_plural': 'Fases de Torneo',
                'db_table': 'fases_torneo',
                'ordering': ['torneo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTorneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Grupo A, Grupo B', max_length=20)),
                ('fase', models.ForeignKey(limit_choices_to={'tipo': 'Grupos'}, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='tournaments.fasetorneo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupos_torneo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionTorneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Pago'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Eliminado', 'Eliminado del Torneo')], default='Pendiente', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ranking_inicial', models.PositiveIntegerField(blank=True, help_text='Posición de siembra (1=mejor)', null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_j1', to='players.jugador')),
                ('jugador2', models.ForeignKey(blank=True, help_text='Solo para torneos de dobles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_j2', to='players.jugador')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripciones_torneo',
                'ordering': ['fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_torneo', models.CharField(help_text='Código único del torneo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del torneo', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('Eliminacion', 'Eliminación Directa'), ('Ranking', 'Ranking/Liga'), ('Grupos', 'Grupos + Eliminación')], max_length=20)),
                ('modalidad', models.CharField(choices=[('Individual', 'Individual (1 vs 1)'), ('Dobles', 'Dobles (2 vs 2)')], default='Dobles', max_length=20)),
                ('estado', models.CharField(choices=[('Inscripcion', 'Inscripción Abierta'), ('Preparacion', 'En Preparación'), ('En_Curso', 'En Curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Inscripcion', max_length=20)),
                ('min_participantes', models.PositiveIntegerField(default=4, help_text='Mínimo de participantes/equipos', validators=[django.core.validators.MinValueValidator(2)])),
                ('max_participantes', models.PositiveIntegerField(default=32, help_text='Máximo de participantes/equipos', validators=[django.core.validators.MaxValueValidator(128)])),
                ('sets_para_ganar', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('juegos_para_ganar_set', models.PositiveIntegerField(default=6)),
                ('numero_grupos', models.PositiveIntegerField(blank=True, help_text='Solo para torneos con grupos', null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(16)])),
                ('clasifican_por_grupo', models.PositiveIntegerField(blank=True, help_text='Cuántos clasifican de cada grupo', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha de inicio del torneo')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha estimada de finalización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=0, help_text='Costo de inscripción por participante/equipo', max_digits=10)),
                ('premio_descripcion', models.TextField(blank=True, help_text='Descripción de premios')),
                ('permite_inscripcion_individual', models.BooleanField(default=False, help_text='Para dobles: permitir inscripción sin pareja')),
                ('sorteo_publico', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('canchas', models.ManyToManyField(blank=True, help_text='Canchas disponibles para el torneo', related_name='torneos', to='scoring.cancha')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'db_table': 'torneos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PartidoTorneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Regular', 'Partido Regular'), ('Desempate', 'Partido de Desempate'), ('Clasificacion', 'Partido por Posición')], default='Regular', max_length=20)),
                ('orden_en_fase', models.PositiveIntegerField(help_text='Orden dentro de la fase')),
                ('es_lado_equipo1', models.BooleanField(blank=True, help_text='True si el ganador va como equipo1 en siguiente partido', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('cancha_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.cancha')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='tournaments.fasetorneo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='tournaments.grupotorneo')),
                ('inscripcion_equipo1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo1', to='tournaments.inscripciontorneo')),
                ('inscripcion_equipo2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo2', to='tournaments.inscripciontorneo')),
                ('partido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partido_torneo', to='scoring.partido')),
                ('siguiente_partido', models.ForeignKey(blank=True, help_text='Partido al que avanza el ganador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_previos', to='tournaments.partidotorneo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_torneo', to='tournaments.torneo')),
            ],
            options={
                'verbose_name': 'Partido de Torneo',
                'verbose_name_plural': 'Partidos de Torneo',
                'db_table': 'partidos_torneo',
                'ordering': ['fase', 'orden_en_fase'],
            },
        ),
        migrations.AddField(
            model_name='inscripciontorneo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='tournaments.torneo'),
        ),
        migrations.AddField(
            model_name='grupotorneo',
            name='inscripciones',
            field=models.ManyToManyField(related_name='grupos', to='tournaments.inscripciontorneo'),
        ),
        migrations.AddField(
            model_name='fasetorneo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='tournaments.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripciontorneo',
            unique_together={('torneo', 'jugador1', 'jugador2')},
        ),
        migrations.AlterUniqueTogether(
            name='grupotorneo',
            unique_together={('fase', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='fasetorneo',
            unique_together={('torneo', 'orden')},
        ),
        migrations.CreateModel(
            name='ClasificacionTorneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posicion_final', models.PositiveIntegerField()),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('partidos_ganados', models.PositiveIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveIntegerField(default=0)),
                ('sets_ganados', models.PositiveIntegerField(default=0)),
                ('sets_perdidos', models.PositiveIntegerField(default=0)),
                ('juegos_ganados', models.PositiveIntegerField(default=0)),
                ('juegos_perdidos', models.PositiveIntegerField(default=0)),
                ('premio_descripcion', models.TextField(blank=True)),
                ('premio_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.inscripciontorneo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='tournaments.torneo')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'db_table': 'clasificaciones_torneo',
                'ordering': ['torneo', 'posicion_final'],
                'unique_together': {('torneo', 'posicion_final'), ('torneo', 'inscripcion')},
            },
        ),
    ]
