# Generated by Django 4.2.7 on 2025-08-01 05:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "edad",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Edad del jugador",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                8, message="La edad mínima es 8 años"
                            ),
                            django.core.validators.MaxValueValidator(
                                120, message="La edad máxima es 120 años"
                            ),
                        ],
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        help_text="Sexo del jugador",
                        max_length=1,
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, help_text="Teléfono de contacto", max_length=20
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario Django asociado (obligatorio)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jugador",
                "verbose_name_plural": "Jugadores",
                "db_table": "jugadores",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
    ]
